### ISSUE TITLE
per-action required properties not applying correctly

### ISSUE THREAD

**Issue by kimbernator** [chefspec/chefspec#1004]
We currently have a number of resources like this to remove specific cron jobs if they exist:

```ruby
cron 'reboot' do
  action :delete
end
```

As such, we have this spec:
```ruby
it 'deletes a cron entry named reboot' do
  expect(chef_run).to delete_cron('reboot')
end
```

When chefspec runs, the following failure is generated:
```
  1) <cookbook::recipe> Disable rebooting deletes a cron entry named reboot
     Failure/Error: expect(chef_run).to delete_cron('reboot')

     Chef::Exceptions::ValidationFailed:
       command is a required property
     # ./spec/unit/recipes/disable_reboot_spec.rb:36:in `block (3 levels) in <top (required)>'
```

full stacktrace:
```
     Chef::Exceptions::ValidationFailed:
       command is a required property
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/property.rb:427:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/property.rb:369:in `call'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/property.rb:592:in `command'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/resource.rb:528:in `block in identity'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/resource.rb:527:in `each'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chef-16.10.8/lib/chef/resource.rb:527:in `identity'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:209:in `block in find_resource'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:208:in `reverse_each'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:208:in `each'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:208:in `find'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:208:in `find_resource'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/matchers/resource_matcher.rb:161:in `resource'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/matchers/resource_matcher.rb:48:in `matches?'
     # ./spec/unit/recipes/disable_reboot_spec.rb:36:in `block (3 levels) in <top (required)>'
     # /home/jenkins/.rvm/gems/ruby-2.7.0@executor-8/gems/chefspec-9.2.1/lib/chefspec/api/core.rb:18:in `block in <module:Core>'
```

I'm running the newest version of chef workstation (21.2.259), but just to be sure I went in to validate the code locally and found the following in `/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/resource/cron/_cron_shared.rb`:
```ruby
property :command, String,
  description: "The command to be run, or the path to a file that contains the command to be run.",
  identity: true,
  required: [:create]
```

So it seems like the syntax for requiring a property only for specific actions isn't being respected.

version information:

Chef Workstation version: 21.2.259
Chef Infra Client version: 16.10.8
Chef InSpec version: 4.26.4
Chef CLI version: 3.1.0
Chef Habitat version: 1.6.181
Test Kitchen version: 2.10.0
Cookstyle version: 7.7.2
Chefspec version: 9.2.1

**Comment by kimbernator** [comment]
After creating a spec for another resource with a similar per-action requirement, it seems like this might be specific to the cron resource.

**Comment by lamont-granquist** [comment]
Yeah this is core chef this has nothing directly to do with chefspec
