### ISSUE TITLE
chef 17 incompatibility

### ISSUE THREAD

**Issue by 0nky0** [chefspec/chefspec#1012]
below snippet shows chef, chefspec and ruby version that i am using

```shell
$ bundle list | grep -E 'chef(spec)? '
  * chef (16.13.16)
  * chefspec (9.2.1)

$ ruby --version
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]
```

when i execute chefspec, it runs successfully.
when updating to the latest chef version (17.0.242), chefspec fails to run

```shell
$ bundle exec rspec ./cookbooks/foo

An error occurred while loading ./cookbooks/foo/spec/recipes/foo_spec.rb.
Failure/Error:
  def action(sym, &block)
    inject_actions(sym)
    super
  end

ArgumentError:
  unknown keyword: :description
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec/extensions/chef/resource.rb:143:in `action'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resource/alternatives.rb:125:in `<class:Alternatives>'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resource/alternatives.rb:24:in `<class:Resource>'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resource/alternatives.rb:23:in `<class:Chef>'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resource/alternatives.rb:22:in `<top (required)>'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resources.rb:19:in `require_relative'
# ./gems/ruby/2.7.0/gems/chef-17.0.242/lib/chef/resources.rb:19:in `<top (required)>'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:6:in `require'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec/solo_runner.rb:6:in `<top (required)>'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec/server_runner.rb:7:in `require_relative'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec/server_runner.rb:7:in `<top (required)>'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec.rb:69:in `require_relative'
# ./gems/ruby/2.7.0/gems/chefspec-9.2.1/lib/chefspec.rb:69:in `<top (required)>'
# ./cookbooks/foo/spec/spec_helper.rb:4:in `require'
# ./cookbooks/foo/spec/spec_helper.rb:4:in `<top (required)>'
# ./cookbooks/foo/spec/recipes/foo_spec.rb:3:in `require_relative'
# ./cookbooks/foo/spec/recipes/foo_spec.rb:3:in `<top (required)>'
```

**Comment by 0nky0** [comment]
issue is resolved when upgrading to chef version 17.1.35
