### ISSUE TITLE
Improve dsc_resource To Handle ps_credential

### ISSUE THREAD

**Issue by sean-horn** [chefspec/chefspec#695]
---Summary---
Many dsc_resources use the PSCredential to hide passwords needed by the resources on Windows systems. Currently, it appears that ChefSpec's dsc_resource matcher may not be able to handle this usage.

The code for ps_credential can be found here
https://github.com/chef/chef/commit/377ec3040dd3ec2b4fc4b4e66d5ca71ab79dd1b7

It's used like this in a recipe, test-dsc::default, which converges successfully.

```
dsc_resource 'useradd' do
  resource :user
  property :username, 'Foobar1'
  property :fullname, 'Foobar1'
  property :password, ps_credential('P@assword!')
  property :ensure, 'present'
end
```

If I write the ChefSpec to test that recipe as

```
require 'chefspec'

RSpec.configure do |config|
  config.platform = 'windows'
  config.version  = '2012R2'
end

describe 'test-dsc::default' do
  let(:chef_run) { ChefSpec::ServerRunner.converge(described_recipe) }

  it 'runs dsc_resource with the user resource' do

    expect(chef_run).to run_dsc_resource('useradd').with(
      resource: :user,
      properties: {
        username: 'Foobar1',
        fullname: 'Foobar1',
        password: ps_credential('P@assword!'),
        ensure: 'present'
      })
  end
end
```

and then test, I get

```
PS C:\Users\Administrator\cookbooks\test-dsc> chef exec rspec
F

Failures:

  1) test-dsc::default runs dsc_resource with the user resource
     Failure/Error: password: ps_credential('P@assword!'),

     NoMethodError:
       undefined method `ps_credential' for #<RSpec::ExampleGroups::TestDscDefault:0x456c510>
     # ./spec/default_spec.rb:22:in `block (2 levels) in <top (required)>'

Finished in 10.41 seconds (files took 3.58 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/default_spec.rb:15 # test-dsc::default runs dsc_resource with the user resource
```

If I try to get smart and define the identical PSCredential object like this

```
describe 'test-dsc::default' do
  let(:chef_run) { ChefSpec::ServerRunner.converge(described_recipe) }
  let(:credential) {Chef::Util::Powershell::PSCredential.new('placeholder','P@assword!')}


  it 'runs dsc_resource with the user resource' do

    expect(chef_run).to run_dsc_resource('useradd').with(
      resource: :user,
      properties: {
        username: 'Foobar1',
        fullname: 'Foobar1',
        password: credential,
        ensure: 'present'
      })
  end
end
```

then I get this error. The password has been encrypted at this point with https://github.com/chef/chef/commit/377ec3040dd3ec2b4fc4b4e66d5ca71ab79dd1b7#diff-60a0a963e661ae756510d65793239599R25 which may have a salt or something, so the encrypted passwords in Chef::Util::Powershell::PSCredential:0x495cb10 and Chef::Util::Powershell::PSCredential:0x2fcd810 do not match.

```
PS C:\Users\Administrator\cookbooks\test-dsc> chef exec rspec
F

Failures:

  1) test-dsc::default runs dsc_resource with the user resource
     Failure/Error:
       expect(chef_run).to run_dsc_resource('useradd').with(
         resource: :user,
         properties: {
           username: 'Foobar1',
           fullname: 'Foobar1',
           password: credential,
           ensure: 'present'
         })

       expected "dsc_resource[useradd]" to have parameters:

         properties {:username=>"Foobar1", :fullname=>"Foobar1", :password=>#<Chef::Util::Powershell::PSCredential:0x495
cb10 @username="placeholder", @password="P@assword!">, :ensure=>"present"}, was {:username=>"Foobar1", :fullname=>"Fooba
r1", :password=>#<Chef::Util::Powershell::PSCredential:0x2fcd810 @username="placeholder", @password="P@assword!">, :ensu
re=>"present"}
       Diff:
       @@ -1,5 +1,5 @@
        :ensure => "present",
        :fullname => "Foobar1",
       -:password => #<Chef::Util::Powershell::PSCredential:0x495cb10 @username="placeholder", @password="P@assword!">,
       +:password => #<Chef::Util::Powershell::PSCredential:0x2fcd810 @username="placeholder", @password="P@assword!">,
        :username => "Foobar1",
     # ./spec/default_spec.rb:17:in `block (2 levels) in <top (required)>'

Finished in 10.36 seconds (files took 3.53 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/default_spec.rb:15 # test-dsc::default runs dsc_resource with the user resource
```

You can see the difference between the encrypted passwords more clearly, if I tack the `to_psobject` method on to the credential in both the recipe and test and run it again

```
PS C:\Users\Administrator\cookbooks\test-dsc> chef exec rspec
F

Failures:

  1) test-dsc::default runs dsc_resource with the user resource
     Failure/Error: expect(chef_run.resource_collection.to_a[0].to_hash[:properties][:password].to_psobject).to include(
credential.to_psobject)
       expected "New-Object System.Management.Automation.PSCredential('placeholder',('01000000d08c9ddf0115d1118c7a00c04f
c297eb0100000049ee80d9ee5e5f44a9133f71def1a8fc0400000002000000000010660000000100002000000024641c223765caac7a1b6a79049aa2
9ff8f43257d2b4323f31c778be44eacc59000000000e8000000002000020000000fd63174b7e3c87db63a9a9402e3fa8244cc4c88910fd0f1af029e3
a7826307ff20000000a0ab6dffebb5561d3f9464ab90dc4e7d549f430a81d43b8347c948795fe0375f40000000b60425d9facd653c0efa27ba7fdac7
034c0f6efd9aaaedbde2bbcf20db1a4d8bf65601a543bcf5902a5b792543dda76503a1c6c11786b5e1d2e7f08a1bce78e3' | ConvertTo-SecureSt
ring))" to include "New-Object System.Management.Automation.PSCredential('placeholder',('01000000d08c9ddf0115d1118c7a00c
04fc297eb0100000049ee80d9ee5e5f44a9133f71def1a8fc040000000200000000001066000000010000200000000569d031e6eb210955ea1b04640
e375493883aa5ed07b0d6665aea3d3685b756000000000e80000000020000200000006afb6a4465b329fb89be0c74f657c7fb200c38d0e0a8c833f05
2c616fcc77c7120000000c5913003c6832d725b497b9df4efc9a9cdb43916cf9576f5101a994660d2d2af4000000059bed5cc12e0fa6f13ba3c5017e
fd42395e84a021a0085aa65356a425954609a5b97238b61c17384dc28495ceabe7db4be2f12dad13b00e45c676cb2fa877650' | ConvertTo-Secur
eString))"
     # ./spec/default_spec.rb:21:in `block (2 levels) in <top (required)>'

Finished in 10.52 seconds (files took 3.52 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/default_spec.rb:15 # test-dsc::default runs dsc_resource with the user resource
```

**Comment by MichaelStankiewicz** [comment]
Is anyone aware if any progress has been made on this or whether there is any workaround?

**Comment by coderanger** [comment]
This will have to be fixed in Chef itself as the `PsCredential` object doesn't define an `==` operator. The workaround is just don't test that one property.

**Comment by MichaelStankiewicz** [comment]
@coderanger Thanks.  But if I remove this property from my spec file and run the test, I get a failure stating that the property is present in my recipe but not in my test.  So it doesn't appear that simply not testing the property is a workaround at all, unless I'm missing something.

**Comment by coderanger** [comment]
Use something like this:

```ruby
    expect(chef_run).to run_dsc_resource('useradd').with(
      resource: :user,
      properties: include({
        username: 'Foobar1',
        fullname: 'Foobar1',
        ensure: 'present'
      }))

**Comment by MichaelStankiewicz** [comment]
@coderanger This is what I have, but doesn't work.  For example:

**recipe.rb**
dsc_resource '[File]Copy_RepositoryManager_Provider' do
  resource :File
  property :Ensure, 'Present'
  property :DestinationPath, "C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\"
  property :SourcePath,"\\\\my_file_server.domain.com\\share\\Source_Module_Directory"
  property :Type, 'Directory'
  property :Checksum, 'modifiedDate'
  property :MatchSource, true
  property :Recurse, true
  property :PsDscRunAsCredential, ps_credential('user', 'password')  
end

**spec.rb**
it 'runs dsc_resource with the File resource' do
      expect(chef_run).to run_dsc_resource('[File]Copy_RepositoryManager_Provider').with(
        resource: :File,
          properties: {
            Ensure: 'Present',
            DestinationPath: "C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\",
            SourcePath: "\\\\my_file_server.domain.com\\share\\Source_Module_Directory",
            Type: 'Directory',
            Checksum: 'modifiedDate',
            MatchSource: true,
            Recurse: true,            
          }
      )
end

But when I run this via chef exec rspec, I'm getting the following error:

```
Failure/Error:
       expect(chef_run).to run_dsc_resource('[File]Copy_RepositoryManager_Provider').with(
         resource: :File,
           properties: {
             Ensure: 'Present',
             DestinationPath: "C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\",
             SourcePath: "\\\\my_file_server.domain.com\\share\\Source_Module_Directory",
             Type: 'Directory',
             Checksum: 'modifiedDate',
             MatchSource: true,
             Recurse: true,

       expected "dsc_resource[[File]Copy_RepositoryManager_Provider]" to have parameters:

         properties {:Ensure=>"Present", :DestinationPath=>"C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\", :SourcePath=>"\\\\my_file_server.domain.com\\share\\Source_Module_Directory", :Type=>"Directory", :Checksum=>"modifiedDate", :MatchSource=>true, :Recurse=>true}, was {:Ensure=>"Present", :DestinationPath=>"C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\", :SourcePath=>"\\\\my_file_server.domain.com\\share\\Source_Module_Directory", :Type=>"Directory", :Checksum=>"modifiedDate", :MatchSource=>true, :Recurse=>true, :PsDscRunAsCredential=>#<Chef::Util::Powershell::PSCredential:0x00000000067bf678 @username="user", @password="password">}
       Diff:
       @@ -2,6 +2,7 @@
        :DestinationPath => "C:\\Program Files\\WindowsPowerShell\\Modules\\cPSRepositoryManager\\",
        :Ensure => "Present",
        :MatchSource => true,
       +:PsDscRunAsCredential => #<Chef::Util::Powershell::PSCredential:0x00000000067bf678 @username="user", @password="password">,
        :Recurse => true,
        :SourcePath => "\\\\my_file_server.domain.com\\share\\Source_Module_Directory",
        :Type => "Directory",

     # ./spec/unit/recipes/windows2012r2/web_spec.rb:18:in `block (3 levels) in <top (required)>'
```

**Comment by coderanger** [comment]
@MichaelStankiewicz You missed the `include()` around the properties hash. The idea is to use a composed RSpec matcher.

**Comment by MichaelStankiewicz** [comment]
@coderanger Thanks.  But when I do this, I get the following error.  It looks like chefspec doesn't like the 'include(' or the closing ')'.

```
Failure/Error: load file

SyntaxError:
  C:/users/me/repo/cookbooks/my_cookbook/spec/unit/recipes/windows2012r2/web_spec.rb:20: syntax error, unexpected ( arg, expecting keyword_do or '{' or '('
           properties: include ({
                                ^
  C:/users/me/repo/cookbooks/my_cookbook/spec/unit/recipes/windows2012r2/web_spec.rb:29: syntax error, unexpected ')', expecting keyword_end
        )
         ^
```

**Comment by coderanger** [comment]
You can't have a space. Please just look at the example I gave you.

**Comment by MichaelStankiewicz** [comment]
Ahh...that worked!  Thanks for your help with this one.
