### ISSUE TITLE
Setting node.chef_environment is more difficult than it should be

### ISSUE THREAD

**Issue by acsportstec** [chefspec/chefspec#774]
Chefspec appears to be ignoring environment variables, when running for one cookbook. We have a cookbook that is calling a data bag like so:

**default.rb**
`config_data = data_bag_item('elasticsearch', 'config')['group'][server_group][node.chef_environment]`

which I have expanded to:

```
tmp_data = data_bag_item('elasticsearch', 'config')['group']

tmp_data_1 = tmp_data[server_group]
config_data = tmp_data_1[node.chef_environment]
```

**Example data bag:**

```
"group": {
    "groupA": {
      "prod": {
        "cluster_name": "clusterA",
      },
      "stage": {
        "cluster_name": "clusterStageA",
      },
  }
```

chefspec:

```
describe 'role_elasticsearch::ebs' do
  context 'when in stage' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new do |node|
        env = Chef::Environment.new
        env.name 'stage'
        allow(node).to receive(:chef_environment).and_return(env.name)
        allow(Chef::Environment).to receive(:load).and_return(env)
        node.set['name'] = 's-test-blarblar'
// I have also tried using combinations of the following:
        node.set['chef_environment'] = 'stage'
        node.set['node']['chef_environment'] = 'stage'
        node.normal['chef_environment'] = 'stage'
        node.normal['node']['chef_environment'] = 'stage'
      end.converge('role_elasticsearch::ebs')
    end

    before do
      stub_data_bag_item('elasticsearch', 'config').and_return({
          id: 'config',
          install: {
            default: {
            }
          },
          group: {
            GroupA: {
              stage: {}
            }
          }
        })
    end

    it 'will include my recipe' do
      expect(chef_run).to include_recipe('myrecipe')
    end
  end
end
```

However I am getting the following error when running the tests:

```
Recipe Compile Error in /var/folders/k5/2wstr0w96w99h0ykf1mltmp80000gn/T/d20161025-2220-7c9e2l/cookbooks/role_elasticsearch/recipes/ebs.rb
===========================================================================

NoMethodError
-------------
undefined method []' for nil:NilClass

Cookbook Trace:
---------------
  /var/folders/k5/2wstr0w96w99h0ykf1mltmp80000gn/T/d20161025-2220-7c9e2l/cookbooks/role_elasticsearch/recipes/ebs.rb:13:in from_file'

Relevant File Content:
----------------------
/var/folders/k5/2wstr0w96w99h0ykf1mltmp80000gn/T/d20161025-2220-7c9e2l/cookbooks/role_elasticsearch/recipes/ebs.rb:

  6:  #
  7:  # All rights reserved - Do Not Redistribute
  8:  #
  9:  server_group = node.name.split('-')[1]
 10:  tmp_data = data_bag_item('elasticsearch', 'config')['group']
 11:
 12:  tmp_data_1 = tmp_data[server_group]
 13>> config_data = tmp_data_1[node.chef_environment]
 14:
 15:  data_size = config_data['data_size'] || 10
 16:  data_iops = config_data['data_iops'] || 101
 17:  data_device = config_data['data_device'] || '/dev/xvdg'
 18:  log_device = config_data['log_device'] || '/dev/xvdh'
 19:
 20:  node.normal['ebs']['volumes'] = [
 21:    {
 22:      'user'         => 'myuser',

Platform:
---------
x86_64-darwin13

F

Failures:

  1) role_elasticsearch::ebs when in stage will include myrecipe recipe
     Failure/Error:
             ChefSpec::SoloRunner.new do |node|

               env = Chef::Environment.new
               env.name 'stage'
               allow(node).to receive(:chef_environment).and_return(env.name)
               allow(Chef::Environment).to receive(:load).and_return(env)

               node.set['name'] = 's-test-blarblar'
               node.set['chef_environment'] = 'stage'
               node.set['node']['chef_environment'] = 'stage'

     NoMethodError:
       undefined method []' for nil:NilClass
     # /var/folders/k5/2wstr0w96w99h0ykf1mltmp80000gn/T/d20161025-2220-7c9e2l/cookbooks/role_elasticsearch/recipes/ebs.rb:13:in `from_file'
     # ./spec/recipes/ebs_spec.rb:23:in block (3 levels) in <top (required)>'
     # ./spec/recipes/ebs_spec.rb:42:in block (3 levels) in <top (required)>'

Finished in 1.43 seconds (files took 2.3 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/recipes/ebs_spec.rb:41 # role_elasticsearch::ebs when in stage will include myrecipe recipe


  No Chef resources found, skipping coverage calculation...
```

It appears that the **node.chef_environment** is not set no matter what combination I use.

**Comment by rneu31** [comment]
I'm not familiar with `stub_data_bag_item` and am instead using https://github.com/chef/chef-vault-testfixtures to point to stubbed data bags in `test/integration/data_bags`... but..

I have something that looks to be the same as your pattern in production:
```
let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'redhat', version: '7.2') do |node|
      # Chefspec overrides the environment as 'chefspec'. Change the env back
      # to _default.
      env = Chef::Environment.new
      env.name '_default'
      allow(node).to receive(:chef_environment).and_return(env.name)
      allow(Chef::Environment).to receive(:load).and_return(env)

    end.converge(described_recipe)
  end
```

Have you added a `puts "Env: #{node.chef_environment}"` in your `default.rb` to see what value it was receiving? Sometimes the `undefined method []' for nil:NilClass` errors are coming from somewhere you would have never expected...

**Comment by lamont-granquist** [comment]
chef_environment isn't a typical attribute, so `node.chef_environment = "myenvironment"` needs to be used instead of `node.automatic["chef_environment"] = "myenvironment"`.  the latter will never work and is not a bug.

in chefspec though that results in:

```
================================================================================
Error expanding the run_list:
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::EnvironmentNotFound: Environment 'myenvironment' could not be loaded from disk

System Info:
------------
chef_version=14.1.1
platform=chefspec
platform_version=0.6.1
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
program_name=/Users/lamont/.rvm/gems/ruby-2.5.1/bin/rspec
executable=/Users/lamont/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks

F

Failures:

  1) test::default
     Failure/Error: cached(:chef_run) { ChefSpec::SoloRunner.new { |node| node.chef_environment = "myenvironment" }.converge(described_recipe) }

     Chef::Exceptions::EnvironmentNotFound:
       Environment 'myenvironment' could not be loaded from disk
     # /Users/lamont/oc/chef/lib/chef/environment.rb:265:in `load_from_file'
     # /Users/lamont/oc/chef/lib/chef/environment.rb:241:in `load'
     # /Users/lamont/oc/chef/lib/chef/node.rb:443:in `apply_expansion_attributes'
     # /Users/lamont/oc/chef/lib/chef/node.rb:431:in `expand!'
     # /Users/lamont/oc/chef/lib/chef/policy_builder/expand_node_object.rb:144:in `expand_run_list'
     # /Users/lamont/oc/chef/lib/chef/client.rb:808:in `expanded_run_list'
     # /Users/lamont/.rvm/gems/ruby-2.5.1/gems/chefspec-7.2.1/lib/chefspec/solo_runner.rb:397:in `expand_run_list!'
     # /Users/lamont/.rvm/gems/ruby-2.5.1/gems/chefspec-7.2.1/lib/chefspec/solo_runner.rb:114:in `converge'
     # ./spec/test_spec.rb:4:in `block (2 levels) in <top (required)>'
     # /Users/lamont/.rvm/gems/ruby-2.5.1/gems/chefspec-7.2.1/lib/chefspec/cacher.rb:50:in `instance_eval'
     # /Users/lamont/.rvm/gems/ruby-2.5.1/gems/chefspec-7.2.1/lib/chefspec/cacher.rb:50:in `block in cached'
     # ./spec/test_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.02481 seconds (files took 0.94484 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/test_spec.rb:7 # test::default
```

That results in the need to stub the chef classes directly to work around this issue, which is probably not good UX.

**Comment by coderanger** [comment]
We have instructions on this in the README already, https://github.com/chefspec/chefspec#mocking-out-environments

**Comment by lamont-granquist** [comment]
Yep, I just found those and was coming here to comment and close...
