### ISSUE TITLE
chefspec fails for `windows_package` resource with `windows` >= 3.0.0 as a dependency

### ISSUE THREAD

**Issue by munusamy** [chefspec/chefspec#826]
Hi,

I got the below error for `windows_package` resource and same works fine if `windows` < 3.0.0 as a dependency.

```
1) mycookbook::windows installing a windows package Google Chrome
     Failure/Error: expect(chef_run).to install_windows_package('Google Chrome').with_source('c:\chef\cache\ChromeSetup.msi')

       expected "windows_package[Google Chrome]" to have parameters:

         source "c:\\chef\\cache\\ChromeSetup.msi", was "/Users/testuser/chef-repo/cookbooks/mycookbook/c:\\chef\\cache\\ChromeSetup.msi"
     Shared Example Group: "setup chef-zero run" called from ./spec/unit/recipes/windows_spec.rb:15
     # ./spec/unit/recipes/windows_spec.rb:20:in `block (3 levels) in <top (required)>'
```

**Comment by coderanger** [comment]
Please include your spec code too.

**Comment by munusamy** [comment]
Here is my `recipes/windows.rb`

```
windows_package "Google Chrome" do 
  source "#{Chef::Config[:file_cache_path]}\\ChromeSetup.msi"
  installer_type :msi
  timeout 6000
  options "/passive"
  action :install
end
```

# `spec/unit/recipes/windows_spec.rb`

```
describe 'mycookbook::windows' do
      let(:chef_run) { ChefSpec::ServerRunner.new(platform: 'windows', version: '2012R2', file_cache_path: 'c:\chef\cache').converge(described_recipe) }
      
      it 'installing a windows package Google Chrome' do
        expect(chef_run).to install_windows_package('Google Chrome').with_source('c:\chef\cache\ChromeSetup.msi')
      end
    end
```

**Comment by tas50** [comment]
@munusamy Can you try changing windows_package to just package and report back.

**Comment by munusamy** [comment]
Hi,

I still have the same error.

`recipes/windows.rb`

```
package "Google Chrome" do 
  source "#{Chef::Config[:file_cache_path]}\\ChromeSetup.msi"
  timeout 6000
  options "/passive"
  action :install
end
```

And `spec/unit/recipes/windows_spec.rb`

```
describe 'mycookbook::windows' do
      let(:chef_run) { ChefSpec::ServerRunner.new(platform: 'windows', version: '2012R2', file_cache_path: 'c:\chef\cache').converge(described_recipe) }
      
      it 'installing a windows package Google Chrome' do
        expect(chef_run).to install_package('Google Chrome').with_source('c:\chef\cache\ChromeSetup.msi')
      end
    end
```

I got below result:

```
1) mycookbook::windows installing a windows package Google Chrome
     Failure/Error: expect(chef_run).to install_package('Google Chrome').with_source('c:\chef\cache\ChromeSetup.msi')

       expected "windows_package[Google Chrome]" to have parameters:

         source "c:\\chef\\cache\\ChromeSetup.msi", was "/Users/testuser/chef-repo/cookbooks/mycookbook/c:\\chef\\cache\\ChromeSetup.msi"
     Shared Example Group: "setup chef-zero run" called from ./spec/unit/recipes/windows_spec.rb:15
     # ./spec/unit/recipes/windows_spec.rb:20:in `block (3 levels) in <top (required)>'
```

**Comment by TimCorwin** [comment]
Also affects ChefDK 1.2.22

**Comment by coderanger** [comment]
So two issues, first is `with_source` a custom addition since normally that would be `with(source: 'whatever')`. Second, the cache path is not going to be the same on Windows vs macOS, and you get the cache of where you actually run the specs, not the OS you plan to run the recipe on. 

This should probably be:

```ruby
expect(chef_run).to install_package('Google Chrome').with(source: "#{Chef::Config[:file_cache_path]}\\ChromeSetup.msi")
```

This is a frustratingly useless test, since normally you should do the substitution in your test to confirm it actually worked, but since the cache path is actually variable, you can't do it with that value in particular.
      end

**Comment by munusamy** [comment]
I agree what you said about `file_cache_path` is different on Windows vs macOS.

The same code works fine on `masOS` if I force my `depends 'windows', '~> 2.1.0'` in metadata.rb file of `mycookbook`.

And also the `remote_file` resource works fine on lastest `windows` cookbook for the same `file_cache_path`

`recipes/windows.rb`

```
remote_file "#{Chef::Config[:file_cache_path]}/ChromeSetup.msi" do
  source 'http://192.168.10.11/windows/ChromeSetup.msi'
end
```

`spec/unit/recipes/windows_spec.rb`

```
describe 'mycookbook::windows' do
      let(:chef_run) { ChefSpec::ServerRunner.new(platform: 'windows', version: '2012R2', file_cache_path: 'c:\chef\cache').converge(described_recipe) }
      
      it 'downloads chromesetup from local webserver' do
        expect(chef_run).to create_remote_file('c:\chef\cache\ChromeSetup.msi')
      end
    end
```

And just letting it know, the same code was working fine for the past 8 months with older version of `windows` cookbook.  The recent release of `windows` with `>3.0.0` is having this issue if I'm not wrong.  Let me know if I am missing something here.

**Comment by lamont-granquist** [comment]
something to do with this from the README?

```
# By default ChefSpec sets a new temporary directory for file caching in every run.
# This can be overridden by passing the `file_cache_path` option.
# Note: Resources containing `Chef::Config[:file_cache_path]` in their name or
# attributes, will fail unless this option is specified.
ChefSpec::SoloRunner.new(file_cache_path: Chef::Config[:file_cache_path])
```

**Comment by lamont-granquist** [comment]
dup of #665 which is ultimately a dup of #652
