### ISSUE TITLE
how to properly stub File(:open)

### ISSUE THREAD

**Issue by kplimack** [chefspec/chefspec#852]
what is the proper way to stub out the file?

```
# test
    let(:yaml_file) { double('yaml_content') }

    before do
      allow(File).to receive(:open).with('/tmp/myface/face.yaml').and_return(yaml_file)
      # also tried this
      # allow_any_instance_of(IO).to receive(:read).and_call_original
      # allow_any_instance_of(IO).to receive(:read).with('/tmp/myface/face.yaml').and_return('my fake file content')
    end

    it 'converges successfully' do

      expect { chef_run }.to_not raise_error
    end

## output
    expected no Exception, got #<RSpec::Mocks::MockExpectationError: #<File (class)> received :open with unexpected arguments
         expe...", "wb")
        Please stub a default value first if message might be received with other args as well.
       > with backtrace:
         # ./spec/unit/recipes/default_spec.rb:12:in `new'
         # ./spec/unit/recipes/default_spec.rb:12:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:24:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:24:in `block (3 levels) in <top (required)>'

```

**Comment by kplimack** [comment]
without stubbing it, i get the following error
```
17:47:37        expected no Exception, got #<Errno::EACCES: Permission denied @ rb_sysopen - /tmp/myface/face.yaml> with backtrace:
17:47:37          # /tmp/chefspec20170608-56548-bm2nojfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:63:in `write'
17:47:37          # /tmp/chefspec20170608-56548-bm2nojfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:63:in `write_node_object'
17:47:37          # /tmp/chefspec20170608-56548-bm2nojfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:97:in `block (2 levels) in from_file'
17:47:37          # (eval):2:in `converge_complete'
17:47:37          # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
17:47:37          # ./spec/unit/recipes/default_spec.rb:22:in `block (4 levels) in <top (required)>'
17:47:37          # ./spec/unit/recipes/default_spec.rb:22:in `block (3 levels) in <top (required)>'my_cookbook
```

**Comment by coderanger** [comment]
When stubbing methods that get used by other code in Chef or RSpec you need something like:

```ruby
allow(File).to receive(:open).and_call_original
```

**Comment by kplimack** [comment]
@coderanger im still getting permission denied, but only on jenkins, works fine locally.  
```
23:35:34      Failure/Error: expect { chef_run }.to_not raise_error
23:35:34      
23:35:34        expected no Exception, got #<Errno::EACCES: Permission denied @ rb_sysopen - /tmp/inspec/node.yaml> with backtrace:
23:35:34          # /tmp/chefspec20170608-101027-1m7bwwjfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:70:in `write'
23:35:34          # /tmp/chefspec20170608-101027-1m7bwwjfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:70:in `write_node_object'
23:35:34          # /tmp/chefspec20170608-101027-1m7bwwjfile_cache_path/cookbooks/my_cookbook/recipes/default.rb:104:in `block (2 levels) in from_file'
23:35:34          # (eval):2:in `converge_complete'
23:35:34          # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
23:35:34          # ./spec/unit/recipes/default_spec.rb:24:in `block (4 levels) in <top (required)>'
23:35:34          # ./spec/unit/recipes/default_spec.rb:24:in `block (3 levels) in <top (required)>'my_cookbook
```

**Comment by coderanger** [comment]
Are you sure you have the arguments correct? `allow(File).to receive(:open).with('/tmp/myface/face.yaml', 'w').and_return(yaml_file)`

**Comment by lamont-granquist** [comment]
would need more context to this, and it sounds more like a help request that should go to slack, discourse or stackoverflow and not a bug report
