### ISSUE TITLE
render_file not matching template resource when a node attribute controls whether to create or delete the template

### ISSUE THREAD

**Issue by aogail** [chefspec/chefspec#858]
In one of my cookbooks, I'm using a node attribute to control whether a config file is laid down or deleted during the chef run. The node attribute's default value is nil, in which case the config file is deleted. If the node attribute is set to another value, the config file is created based on a template from the cookbook.

I discovered that in this scenario, the `render_file` matcher does not correctly match the latter case. `create_template` does correctly match, though. I distilled a minimal cookbook to exhibit the issue and posted it on Github: https://github.com/aogail/chefspec-template-or-delete

Chefspec failure output from that repo:

```
  1) chefspec-render-file::default with the optional attribute set creates the config file, verified by render_file
     Failure/Error: expect(chef_run).to render_file(config_path)
       expected Chef run to render "/etc/config.conf"
     # ./spec/unit/recipes/default_spec.rb:42:in `block (3 levels) in <top (required)>'

  2) chefspec-render-file::default with the optional attribute set creates the config file, verified by render_file with content
     Failure/Error: expect(chef_run).to render_file(config_path).with_content(/#{setting}/)
     
       expected Chef run to render "/etc/config.conf" matching:
     
       (?-mix:some_value)
     
       but got:
     
     
        
     # ./spec/unit/recipes/default_spec.rb:46:in `block (3 levels) in <top (required)>'
```

**Comment by coderanger** [comment]
Please include your recipe and spec code as well.

**Comment by aogail** [comment]
@coderanger It's at https://github.com/aogail/chefspec-template-or-delete. Do you mean I should include it somewhere else?

**Comment by coderanger** [comment]
@aogail In general it's best to include it in the issue itself since external repos 1) have a ton of extra files in them and 2) can change under the hood.

**Comment by coderanger** [comment]
Does it work if you use a single resource instead?

```ruby
 13 lines (11 sloc) 299 Bytes
template '/etc/config.conf' do
  variables(
      :setting => node['chefspec-render-file']['setting']
  )
  source 'config.conf.erb'
  action node['chefspec-render-file']['setting'] ? :create : :delete
end
```

Guessing something might be getting overwritten in the internal tracking?

**Comment by aogail** [comment]
Good idea, I'll give that a try.

**Comment by lamont-granquist** [comment]
the render_file matcher finds the `file[<filename>]` resource first and then stops and does not find the `template[<filename>]` resource:

https://github.com/chefspec/chefspec/blob/b402602c9b6510b2e585a608332ce60e6a305e30/lib/chefspec/matchers/render_file_matcher.rb#L85-L87

**Comment by lamont-granquist** [comment]
as far as i can see the node attribute control has nothing to do with this bug...
