### ISSUE TITLE
I cannot get this to work

### ISSUE THREAD

**Issue by abhurtun** [chefspec/chefspec#876]
This is my recepie
```
require 'uri'

uri = ::URI.parse(::URI.unescape(node['chrome']['url']))
has_version = Registry.value_exists?('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome','Version')
version = has_version ? Registry.get_value('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome','Version') : nil
package_name = node['chrome']['package_name'].freeze

windows_package "remove #{package_name}" do
  action :remove
  only_if { version != node['chrome']['version']}
end

windows_package "install #{package_name}" do
  source node['chrome']['url']
  action :install
  installer_type :custom
  options "/silent /install --system-level"
  notifies :run, 'batch[disable_chrome_update]', :delayed
  only_if { version != node['chrome']['version'] && File.exists?("C:\\chef\\rebooted")}
end
```

This is my spec
```
#./spec/chrome_spec.rb

require 'chefspec'

describe 'windows::chrome' do

  package_name = 'Google Chrome'

  let :chef_run do
    ChefSpec::SoloRunner.new(platform: 'windows', version: '2008R2').converge(described_recipe)
  end

  before(:each) do
    allow(File).to receive(:exist?).and_call_original
    allow_any_instance_of(Registry).to receive(:value_exists?).with('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome','Version').and_return(false)
  end

  it "remove package #{package_name} wrong version" do    
    expect(chef_run).to remove_windows_package("remove #{package_name}")
  end

  it "donot remove package #{package_name} if correct version" do
    allow_any_instance_of(Registry).to receive(:value_exists?).with('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome','Version').and_return(true)
    allow_any_instance_of(Registry).to receive(:get_value).with('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome','Version').and_return('56.0.2924.87')
    expect(chef_run).to_not remove_windows_package("remove #{package_name}")
  end

  it "install package #{package_name}" do
    expect(chef_run).to install_windows_package("install #{package_name}")
  end

  it "install package #{package_name} with attributes" do
    expect(chef_run).to install_windows_package("install #{package_name}").with(source: 'http://dl.google.com/release2/5d2ymto5cu0732x7whtdxj4eg4eh3vizgj2yoqeg8t5syby9vmpbu68s3nf6zzdy4koq02usuvochbagkdewuwgk82ix5j9xufb/56.0.2924.87_chrome_installer.exe')
    expect(chef_run).to install_windows_package("install #{package_name}").with(action: [:install])
    expect(chef_run).to install_windows_package("install #{package_name}").with(installer_type: :custom)
    expect(chef_run).to install_windows_package("install #{package_name}").with(options: '/silent /install --system-level')
    expect(chef_run).to notify('batch[disable_chrome_update]').to(:run).delayed
  end
  
  it 'donot disable chrome update if GoogleUpdate.exe doesnot exist' do
    allow(File).to receive(:exist?).and_return(false)
    expect(chef_run).to_not run_batch('disable_chrome_update')
  end
end
```

Error
```
Failures:

  1) windows::chrome donot remove package Google Chrome if correct version
     Failure/Error: expect(chef_run).to_not remove_windows_package("remove #{package_name}")
       expected "windows_package[remove Google Chrome]" actions [:remove] to not exist
     # ./cookbooks/windows/spec/chrome_spec.rb:25:in `block (2 levels) in <top (required)>'

  2) windows::chrome install package Google Chrome
     Failure/Error: expect(chef_run).to install_windows_package("install #{package_name}")
       expected "windows_package[install Google Chrome]" actions [] to include :install
     # ./cookbooks/windows/spec/chrome_spec.rb:29:in `block (2 levels) in <top (required)>'

  3) windows::chrome install package Google Chrome with attributes
     Failure/Error: expect(chef_run).to install_windows_package("install #{package_name}").with(source: 'http://dl.google.com/release2/5d2ymto5cu0732x7whtdxj4eg4eh3vizgj2yoqeg8t5syby9vmpbu68s3nf6zzdy4koq02usuvochbagkdewuwgk82ix5j9xufb/56.0.2924.87_chrome_installer.exe')
       expected "windows_package[install Google Chrome]" actions [] to include :install
     # ./cookbooks/windows/spec/chrome_spec.rb:33:in `block (2 levels) in <top (required)>'
```

**Comment by joerg** [comment]
Hi,

In RSpec you should use, or actually have to use, let to declare variables. So instead of `package_name = ...` use `let :package_name { 'Google Chrome' }`.

**Comment by lamont-granquist** [comment]
This isn't a bug report, and howto questions are better sent to https://stackoverflow.com/questions/tagged/chef, http://community-slack.chef.io/ or https://discourse.chef.io/
