### ISSUE TITLE
ChefSpec crashes when installing gems with no version constraints

### ISSUE THREAD

**Issue by josacar** [chefspec/chefspec#896]
ChefSpec 7.1.2 when including a cookbook that has a `gem` dependency in`metadata.rb` results in crash, ChefSpec 7.1.1 works fine.

For example:

```
name 'glare'
maintainer 'Flywire'
maintainer_email 'engineering@flywire.com'
license 'MIT'
description 'Manages Cloudflare resources via API v4'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.6'

source_url 'https://github.com/peertransfer/glare-cookbook'
issues_url 'https://github.com/peertransfer/glare-cookbook/issues'

supports 'debian'
supports 'ubuntu'
supports 'centos'

chef_version '>= 12.6'

gem 'glare'
```

This is the backtrace:

```
  1) monitoring::default in wadus.com
     Failure/Error: cached(:subject) { runner.converge(described_recipe) }

     NoMethodError:
       undefined method `first' for "glare":String
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:13:in `block (2 levels) in install'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:11:in `each'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:11:in `block in install'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:10:in `each'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:10:in `install'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/cookbook/cookbook_collection.rb:60:in `install_gems'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/policy_builder/expand_node_object.rb:78:in `setup_run_context'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/client.rb:513:in `setup_run_context'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/solo_runner.rb:119:in `converge'
     # ./spec/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/cacher.rb:50:in `instance_eval'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/cacher.rb:50:in `block in cached'
     # ./spec/default_spec.rb:20:in `block (3 levels) in <top (required)>'
```

**Comment by lamont-granquist** [comment]
I can't replicate this on 7.2.1, i correctly either get a working run or the message to include the gem in my bundle.

**Comment by josacar** [comment]
Did you use `gem` without specifying the gem version? @lamont-granquist
