### ISSUE TITLE
ChefSpec crashes when installing gems with no version constraints in MRI 2.3

### ISSUE THREAD

**Issue by josacar** [chefspec/chefspec#897]
ChefSpec 7.1.2 when including a cookbook that has a `gem` dependency in`metadata.rb` and the dependency is not loaded in gem bundle raises uninitialized constant error `Gem::MissingSpecError` as it's MRI 2.4+.

This is the backtrace:

```
  1) monitoring::default in wadus.com
     Failure/Error: cached(:subject) { runner.converge(described_recipe) }

     NameError:
       uninitialized constant Gem::MissingSpecError
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:26:in `rescue in locate_gem'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:25:in `locate_gem'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:18:in `block in install'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:18:in `each'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:18:in `install'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/cookbook/cookbook_collection.rb:60:in `install_gems'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/policy_builder/expand_node_object.rb:78:in `setup_run_context'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chef-12.21.31/lib/chef/client.rb:513:in `setup_run_context'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/solo_runner.rb:119:in `converge'
     # ./spec/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/cacher.rb:50:in `instance_eval'
     # /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/cacher.rb:50:in `block in cached'
     # ./spec/default_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Gem::LoadError:
     #   Could not find 'dnsimple' (>= 4.0) among 170 total gem(s)
     #   Checked in 'GEM_PATH=/Users/selu/code/platform/infra/vendor/bundle', execute `gem env` for more information
     #   /Users/selu/code/platform/infra/vendor/bundle/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/cookbook/gem_installer.rb:25:in `locate_gem'
```

**Comment by lamont-granquist** [comment]
This is not solvable.  You've used bundler to create a closure around all the gems which can possibly be loaded into the ruby VM and you're explicitly trying to load a gem from outside that closure, so bundler correctly fails.  You must add that gem to the bundle.  There's no possible alternative.

**Comment by josacar** [comment]
the error is the `uninitialized constant Gem::MissingSpecError`, that constant doesn't exist in MRI 2.3, thanks anyway.
