### ISSUE TITLE
stubs_for_resource: receive_shell_out unable to render opts

### ISSUE THREAD

**Issue by ehanlon** [chefspec/chefspec#930]
https://github.com/chefspec/chefspec/blob/3fe9a19028b839c7b79b1b25f6d465d81c5ed18b/lib/chefspec/api/stubs_for.rb#L86

While testing that `include_recipe 'homebrew'` is expected, it looks as though it's not able to parse my `opts`.

**Spec Test**
```ruby
context 'macOS 10.13' do
    platform 'mac_os_x', 10.13
    stubs_for_resource('execute[set analytics]') do |resource|
      allow(resource).to receive_shell_out("/usr/local/bin/brew analytics state", {:user=>"vagrant"})
    end
    it { is_expected.to include_recipe 'homebrew' }
end
```

**Result**
```ruby
1) lab_core::azure_cli macOS 10.13
     Failure/Error: it { is_expected.to include_recipe 'homebrew' }
       <execute[set analytics] @name: "set analytics" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :run] @action: [:run] @updated: false @updated_by_last_action: false @source_line: "/var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-39625-1mnh0yq/cookbooks/homebrew/recipes/default.rb:39:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :execute @elapsed_time: 0 @command: "/usr/local/bin/brew analytics off" @backup: 5 @is_guard_interpreter: false @declared_type: :execute @cookbook_name: :homebrew @recipe_name: "default" @environment: #<Chef::DelayedEvaluator:0x00007fc25dcb3b40@/var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-39625-1mnh0yq/cookbooks/homebrew/recipes/default.rb:40> @user: "vagrant" @domain: nil> received :shell_out_compacted with unexpected arguments
         expected: ("/usr/local/bin/brew analytics state")
                  got: ("/usr/local/bin/brew analytics state", {:user=>"vagrant"})
       Diff:
       @@ -1,2 +1,2 @@
       -["/usr/local/bin/brew analytics state"]
       +["/usr/local/bin/brew analytics state", {:user=>"vagrant"}]

     Please stub a default value first if message might be received with other args as well.
     # /var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-39625-1mnh0yq/cookbooks/homebrew/recipes/default.rb:43:in `block (2 levels) in from_file'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/extensions/chef/resource.rb:50:in `run_action'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/solo_runner.rb:122:in `converge'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:76:in `block in <module:Core>'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:208:in `block in included'
     # ./spec/unit/recipes/azure_cli_spec.rb:35:in `block (3 levels) in <top (required)>'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:18:in `block in <module:Core>'
```

**Comment by ehanlon** [comment]
**Spec Test**

```ruby
context 'macOS 10.13' do
    platform 'mac_os_x', 10.13
    stubs_for_resource('execute[set analytics]') do |resource|
      allow(resource).to receive_shell_out("/usr/local/bin/brew analytics state", user: "vagrant")
    end
   it { is_expected.to include_recipe 'homebrew' }
end
```
**Result**

```ruby
1) lab_core::azure_cli macOS 10.13 includes homebrew::default
     Failure/Error: is_expected.to include_recipe 'homebrew'

       <execute[set analytics] @name: "set analytics" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :run] @action: [:run] @updated: false @updated_by_last_action: false @source_line: "/var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-40291-5l5bqb/cookbooks/homebrew/recipes/default.rb:39:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :execute @elapsed_time: 0 @command: "/usr/local/bin/brew analytics off" @backup: 5 @is_guard_interpreter: false @declared_type: :execute @cookbook_name: :homebrew @recipe_name: "default" @environment: #<Chef::DelayedEvaluator:0x00007f8ca0256d20@/var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-40291-5l5bqb/cookbooks/homebrew/recipes/default.rb:40> @user: "vagrant" @domain: nil> received :shell_out_compacted with unexpected arguments
         expected: ("/usr/local/bin/brew analytics state")
              got: ("/usr/local/bin/brew analytics state", {:user=>"vagrant"})
       Diff:
       @@ -1,2 +1,2 @@
       -["/usr/local/bin/brew analytics state"]
       +["/usr/local/bin/brew analytics state", {:user=>"vagrant"}]

        Please stub a default value first if message might be received with other args as well.
     # /var/folders/nj/h1mns6ps2nzgzycv332gyymm0000gn/T/d20180913-40291-5l5bqb/cookbooks/homebrew/recipes/default.rb:43:in `block (2 levels) in from_file'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/extensions/chef/resource.rb:50:in `run_action'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/solo_runner.rb:122:in `converge'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:76:in `block in <module:Core>'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:208:in `block in included'
     # ./spec/unit/recipes/azure_cli_spec.rb:37:in `block (3 levels) in <top (required)>'
     # /Users/eammon/.chefdk/gem/ruby/2.5.0/gems/chefspec-7.3.1/lib/chefspec/api/core.rb:18:in `block in <module:Core>'
```

**Comment by coderanger** [comment]
Okay, let me check the code in more detail :)
